eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true
spring:
  application:
    name: eurekaclient
  boot:
    admin:
      url: http://localhost:9090
server:
  port: 8081
management:
  security:
    enabled: false